export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    overflow: 'hidden',
    backgroundColor: '#f5f6fb',
  },
  header: {
    flexShrink: 0,
    position: 'sticky',
    top: 0,
    zIndex: 12,
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: { xs: 2, md: 3 },
    px: { xs: 2, md: 3 },
    py: { xs: 2, md: 0 },
    minHeight: { md: 76 },
    background:
      'linear-gradient(120deg, rgba(255,255,255,0.78), rgba(255,255,255,0.52))',
    backdropFilter: 'blur(24px)',
    WebkitBackdropFilter: 'blur(24px)',
    borderBottom: '1px solid rgba(255,255,255,0.55)',
    boxShadow: '0 25px 70px rgba(15,23,42,0.18)',
  },
  title: {
    variant: 'h5', // Wait, variant is a prop, not sx. I should remove this from here or assume spread.
    fontWeight: 700,
    color: '#0f172a',
    letterSpacing: '-0.01em',
    textShadow: '0 6px 18px rgba(255,255,255,0.65)',
    mb: { xs: 1, md: 0 },
    textAlign: { xs: 'center', md: 'left' },
  },
  tabs: {
    ml: { xs: 0, md: 2 },
    width: { xs: '100%', md: 'auto' },
    minHeight: 52,
    '& .MuiTabs-flexContainer': {
       justifyContent: { xs: 'center', md: 'flex-start' },
    },
    '& .MuiTab-root': {
      color: '#334155',
      fontWeight: 600,
      textTransform: 'none',
      minHeight: 52,
    },
    '& .Mui-selected': { color: '#0f172a' },
    '& .MuiTabs-indicator': {
      height: 3,
      borderRadius: 999,
      background:
        'linear-gradient(90deg, rgba(14,165,233,0.9), rgba(99,102,241,0.9))',
      boxShadow: '0 6px 18px rgba(99,102,241,0.35)',
    },
  },
  userContainer: {
    ml: { xs: 0, md: 'auto' },
    display: 'flex',
    alignItems: 'center',
    justifyContent: { xs: 'center', md: 'flex-end' },
    gap: 2,
    width: { xs: '100%', md: 'auto' },
  },
  avatar: (isAdmin) => ({
    bgcolor: isAdmin ? '#f57f17' : '#1565c0',
    width: 40,
    height: 40,
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
  }),
  roleBadge: (isAdmin) => ({
    px: 2,
    py: 0.5,
    borderRadius: 2,
    backgroundColor: isAdmin ? '#fff8e1' : '#e3f2fd',
    color: isAdmin ? '#f57f17' : '#1565c0',
    fontWeight: 600,
    border: '1px solid',
    borderColor: isAdmin ? '#ffecb3' : '#bbdefb',
    textTransform: 'capitalize',
  }),
  logoutButton: {
    boxShadow: '0 10px 24px rgba(239,68,68,0.35)',
  },
  contentContainer: (isMapTab) => ({
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    p: !isMapTab ? { xs: 2, md: 3 } : 0,
  }),
  mapWrapper: {
    flex: 1,
    minHeight: 0,
  },
  tableWrapper: {
    flex: 1,
    overflow: 'auto',
  },
};